#!/bin/sh
# ICNS Builder
# Copyright (c) 2022 chris1111. All Right Reserved
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# Vars
apptitle="ICNS Builder"
version="1.0"
# Set Icon directory and file
for files in "$@" ;do
echo "Converting "$@" to ICON file "
Sleep 3
IFS='.' read -ra ADDR <<< "$1"
ICONS_DIR=${ADDR[0]}.iconset
mkdir $ICONS_DIR
echo "Create all other images sizes "
Sleep 2
sips -z 16 16     $1 --out $ICONS_DIR/icon_16x16.png
sips -z 32 32     $1 --out $ICONS_DIR/icon_16x16@2x.png
sips -z 32 32     $1 --out $ICONS_DIR/icon_32x32.png
sips -z 64 64     $1 --out $ICONS_DIR/icon_32x32@2x.png
sips -z 128 128   $1 --out $ICONS_DIR/icon_128x128.png
sips -z 256 256   $1 --out $ICONS_DIR/icon_128x128@2x.png
sips -z 256 256   $1 --out $ICONS_DIR/icon_256x256.png
sips -z 512 512   $1 --out $ICONS_DIR/icon_256x256@2x.png
sips -z 512 512   $1 --out $ICONS_DIR/icon_512x512.png
cp $1 $ICONS_DIR/icon_512x512@2x.png
iconutil -c icns $ICONS_DIR
rm -R $ICONS_DIR

done


